### ISSUE TITLE
ECHR data collection query not getting all data?

### ISSUE THREAD

**Issue by Cloud956** [maastrichtlawtech/extraction_libraries#2]
Example situation - all cases from 01/01/2022 to 02/02/2023 in English. 

Hudoc search - 4016 results 
Hudoc query : [link](https://hudoc.echr.coe.int/app/query/results?query=contentsitename:ECHR%20AND%20(NOT%20(doctype=PR%20OR%20doctype=HFCOMOLD%20OR%20doctype=HECOMOLD))%20AND%20(languageisocode:"ENG")%20AND%20(kpdate>="2022-01-01T00:00:00.0Z"%20AND%20kpdate<="2023-02-02T00:00:00.0Z")&select=sharepointid,Rank,ECHRRanking,languagenumber,itemid,docname,doctype,application,appno,conclusion,importance,originatingbody,typedescription,kpdate,kpdateAsText,documentcollectionid,documentcollectionid2,languageisocode,extractedappno,isplaceholder,doctypebranch,respondent,advopidentifier,advopstatus,ecli,appnoparts,sclappnos&sort=&start=0&length=1&rankingModelId=11111111-0000-0000-0000-000000000000)

Our search - 3559 results
Our query :  [link](https://hudoc.echr.coe.int/app/query/results?query=(contentsitename=ECHR)%20AND%20(kpdate>="2022-01-01T00:00:00.0Z"%20AND%20kpdate<="2023-02-02T00:00:00.0Z")%20AND%20(documentcollectionid2:"JUDGMENTS"%20OR%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20documentcollectionid2:"COMMUNICATEDCASES"%20OR%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20documentcollectionid2:"DECISIONS"%20OR%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20documentcollectionid2:"CLIN")%20AND%20(languageisocode:"ENG")&select=itemid,applicability,appno,article,conclusion,docname,doctype,doctypebranch,ecli,importance,judgementdate,languageisocode,originatingbody,violation,nonviolation,extractedappno,scl,publishedby,representedby,respondent,separateopinion,sharepointid,externalsources,issue,referencedate,rulesofcourt,DocId,WorkId,Rank,Author,Size,Path,Description,Write,CollapsingStatus,HighlightedSummary,HighlightedProperties,contentclass,PictureThumbnailURL,ServerRedirectedURL,ServerRedirectedEmbedURL,ServerRedirectedPreviewURL,FileExtension,ContentTypeId,ParentLink,ViewsLifeTime,ViewsRecent,SectionNames,SectionIndexes,SiteLogo,SiteDescription,deeplinks,SiteName,IsDocument,LastModifiedTime,FileType,IsContainer,WebTemplate,SecondaryFileExtension,docaclmeta,OriginalPath,EditorOWSUSER,DisplayAuthor,ResultTypeIdList,PartitionId,UrlZone,AAMEnabledManagedProperties,ResultTypeId,rendertemplateid&sort=itemid%20Ascending&start=0&length=1)

Difference? 

Our case query contains this:
                  (documentcollectionid2:"JUDGMENTS" OR '\
                 'documentcollectionid2:"COMMUNICATEDCASES" OR '\
                 'documentcollectionid2:"DECISIONS" OR '\
                 'documentcollectionid2:"CLIN")
                 
Hudoc search does not contain this.  Is this the intended behaviour?

**Comment by shashankmc** [comment]
@Cloud956  is this issue resolved? If yes, can we close this issue?

**Comment by Cloud956** [comment]
Yes, I will close this issue.
