### ISSUE TITLE
Python scripts for automation of web scraping operative part , citations and paragraph numbers from the eur-lex.europa.eu website for the purpose of path analysis .

### ISSUE THREAD

**Issue by venvis** [maastrichtlawtech/extraction_libraries#5]
There are three python files :

1.operative_extractions.py- This is a python script with a class that takes a Celex id when initializing the class and returns the operative part , scraped from the web link of the respective Celex ID.The purpose of the different functions within the class is to overcome the different html page structures and syntax of different web pages , accordingly looping the respective page of the given celex id through each structure until it gets the operative part from the website. All the functions are of return type 
`->list`

2.para.py-This python script extracts the Paragraph (P) numbers of the citations and returns them in a list only if they are found else it returns an empty list.

3.Citations.py-This python script extracts the  citations(CELEX ID) and returns them in a list only if they are found else it returns an empty list.

**Comment by shashankmc** [comment]
This is implemented in cellar_extractor.
