### ISSUE TITLE
Updated code for extraction of Operative Part from the documents of the respected Celex Id's for purpose of path analysis and  topic modelling. 

### ISSUE THREAD

**Issue by venvis** [maastrichtlawtech/extraction_libraries#7]
This includes three python files . 
- Python file for extraction/scraping of operative part **operative_extraction.py**
- Python file containing the Class for writing it into a json,csv and txt file (Json and txt has been commented for now ) **output.py**
- Python file which calls the class to write the operative part into the respective files , reading the Celex id's from a tsv file. **test_output.py**

**Comment by shashankmc** [comment]
@venvis is this completed? If yes, please close this issue.
